# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0006_auto_20160409_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('descripcion', models.CharField(max_length=100)),
                ('id_accion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.Accion')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_personal', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermisoModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.Modulo')),
                ('id_permiso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.Permiso')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAdministrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=9)),
                ('correo', models.CharField(max_length=60, unique=True)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('nacimiento', models.DateField()),
                ('contra', models.CharField(max_length=120)),
                ('foto', models.ImageField(blank=True, default='img_personal/no-img.jpg', upload_to='img_personal')),
                ('id_permiso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.Permiso')),
            ],
        ),
        migrations.AddField(
            model_name='bitacora',
            name='id_personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.PersonalAdministrativo'),
        ),
    ]
