# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_permisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Permisos',
            new_name='Modulo',
        ),
        migrations.RenameModel(
            old_name='Modulos',
            new_name='Permiso',
        ),
        migrations.AddField(
            model_name='permisomodulo',
            name='id_modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.Modulo'),
        ),
        migrations.AddField(
            model_name='permisomodulo',
            name='id_permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.Permiso'),
        ),
    ]
