# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_personaladministrativo_contra'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaladministrativo',
            name='contra',
            field=models.CharField(default='rudeware', max_length=120),
        ),
    ]
