# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_personaladministrativo_contra'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='id_user',
            field=models.CharField(default='1', max_length=120),
        ),
    ]
