# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20160407_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAdministrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=9)),
                ('correo', models.CharField(max_length=60, unique=True)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('nacimiento', models.DateField()),
                ('contra', models.CharField(max_length=120)),
                ('foto', models.CharField(max_length=100)),
                ('id_permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.DO_NOTHING, to='login.Permiso')),
            ],
        ),
    ]
