# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_myuser_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permisomodulo',
            old_name='id_modulo',
            new_name='pk_id_modulo',
        ),
        migrations.RenameField(
            model_name='permisomodulo',
            old_name='id_permiso',
            new_name='pk_id_permiso',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='id_user',
            field=models.CharField(default='0', max_length=120),
        ),
        migrations.AlterField(
            model_name='personaladministrativo',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=9),
        ),
    ]
