# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20160421_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permisomodulo',
            old_name='pk_id_modulo',
            new_name='id_modulo',
        ),
        migrations.RenameField(
            model_name='permisomodulo',
            old_name='pk_id_permiso',
            new_name='id_permiso',
        ),
    ]
