# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_comentario'),
        ('login', '0005_auto_20160407_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('descripcion', models.CharField(max_length=100)),
                ('id_accion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.Accion')),
                ('id_personal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.PersonalAdministrativo')),
            ],
        ),
    ]
