# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=9)),
                ('correo', models.CharField(max_length=60, unique=True)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('contra', models.CharField(max_length=120)),
                ('ingreso', models.DateField()),
                ('estado', models.CharField(choices=[('on', 'Activo'), ('off', 'Inactivo')], max_length=8)),
            ],
        ),
    ]
