# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_almacen'),
        ('cliente', '0002_accion_bitacoracliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calaficiacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.DecimalField(decimal_places=1, max_digits=2)),
                ('fecha', models.DateTimeField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.Cliente')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.Producto')),
            ],
        ),
    ]
