# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_almacen'),
        ('cliente', '0003_calaficiacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=150)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(blank=True, choices=[('show', 'Aceptado'), ('hide', 'Rechado')], max_length=9)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.Cliente')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.Producto')),
            ],
        ),
    ]
