# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('on', 'Activo'), ('off', 'Inactivo')], default='on', max_length=8),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=9),
        ),
    ]
