# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20160408_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ingreso',
            field=models.DateField(auto_now_add=True),
        ),
    ]
