# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20160409_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contra',
        ),
    ]
