# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0010_almacen'),
        ('cliente', '0004_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('estado', models.IntegerField(choices=[('on', 'Realizado'), ('off', 'Pendiente')])),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.Cliente')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.Producto')),
            ],
        ),
    ]
