# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='carrito',
            name='estado',
            field=models.IntegerField(choices=[('done', 'Realizado'), ('off', 'Cancelado'), ('on', 'Pendiente')]),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compra.Carrito'),
        ),
    ]
