# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Proveedor'),
        ),
    ]
