# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20160406_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='img',
            field=models.ImageField(default='img_productos/no-img.jpg', upload_to='img_productos'),
        ),
    ]
