# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20160406_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='img',
            field=models.ImageField(blank=True, upload_to='img_productos'),
        ),
    ]
