# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_auto_20160406_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, default='img_productos/no-img.jpg', upload_to='img_productos')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.Categoria')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.Proveedor')),
            ],
        ),
    ]
