# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('vendidos', models.IntegerField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.Producto')),
            ],
        ),
    ]
