# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_remove_categoria_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='imagen',
            field=models.ImageField(blank=True, default='img_proveedores/no-img.jpg', upload_to='img_proveedores'),
        ),
    ]
